version: '3.8'

services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.13-2.7.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  auth-service:
    build: ./auth-service
    ports:
      - "8081:8081"
    environment:
      KAFKA_BROKER: kafka:9092
    depends_on:
      - kafka

  venue-service:
    build: ./venue-service
    ports:
      - "8082:8082"
    environment:
      KAFKA_BROKER: kafka:9092
    depends_on:
      - kafka

  class-service:
    build: ./class-service
    ports:
      - "8083:8083"
    environment:
      KAFKA_BROKER: kafka:9092
    depends_on:
      - kafka

  booking-service:
    build: ./booking-service
    ports:
      - "8084:8084"
    environment:
      KAFKA_BROKER: kafka:9092
    depends_on:
      - kafka

  user-service:
    build: ./user-service
    ports:
      - "8085:8085"
    environment:
      KAFKA_BROKER: kafka:9092
    depends_on:
      - kafka

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - auth-service
      - venue-service
      - class-service
      - booking-service
      - user-service