version: '3.8'

services:
  user-db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: userdb
    ports:
      - "5432:5432"
    volumes:
      - user-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  user-service:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      user-db:
        condition: service_healthy
    command: ["sh", "-c", "until pg_isready -h user-db -U postgres; do sleep 1; done; psql -h user-db -U postgres -d userdb -c 'CREATE TABLE IF NOT EXISTS users (id SERIAL PRIMARY KEY, name VARCHAR(100), email VARCHAR(100) UNIQUE, password VARCHAR(100));'; ./user-service"]

volumes:
  user-db-data: