version: '3.8'

services:
  class-db:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - class-db-data:/data/db

  class-service:
    build: .
    ports:
      - "8083:8083"
    depends_on:
      - class-db

volumes:
  class-db-data: