version: '3.8'

services:
  booking-db:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - booking-db-data:/data/db

  booking-service:
    build: .
    ports:
      - "8084:8084"
    depends_on:
      - booking-db

volumes:
  booking-db-data: